name: Deploy Jupyter Book (MyST)

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -U jupyter-book mystmd

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Debug build output
        run: |
          echo "=== ROOT ==="
          ls
          echo "=== BUILD ==="
          ls -R _build || echo "no _build folder"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
